name: tuned-switcher
base: core22
adopt-info: tuned-switcher
grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: ppc64el

apps:
  tuned-switcher:
    command: usr/bin/tuned-switcher
    command-chain: [bin/desktop-launch]
    common-id: org.easycoding.TunedSwitcher
    desktop: usr/share/applications/org.easycoding.TunedSwitcher.desktop
    plugs:
      - desktop
      - desktop-legacy
      - unity7
      - wayland
      - x11
      - tuned-dbus
      - systemd-dbus
    slots:
      - tuned-dbus
      - systemd-dbus

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - fonts-ubuntu
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  tuned-switcher:
    after: 
      - desktop-qt5
    plugin: cmake
    source: https://github.com/EasyCoding/tuned-switcher.git
    source-type: git
    parse-info:
      - usr/share/metainfo/org.easycoding.TunedSwitcher.metainfo.xml
    build-packages:
      - g++
      - make
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
    stage-packages:
      - dbus
      - dbus-x11
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5svg5
      - libqt5widgets5
      - libx11-6
      - libxcb1
      - libxkbcommon0
      - qtwayland5
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DCMAKE_INSTALL_PREFIX=/usr
    organize:
      usr/share/qt5/translations/*.qm: usr/share/tuned-switcher/translations/

slots:
  tuned-dbus: # used to communicate with the TuneD service
    interface: dbus
    bus: system
    name: com.redhat.tuned

  systemd-dbus: # used to track the TuneD service status and to run/stop it
    interface: dbus
    bus: system
    name: org.freedesktop.systemd1
